spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ebook-test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    properties:
      hibernate.hbm2ddl.auto: create
#        show_sql: true
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.orm.jdbc.bind: trace